// Most-visited pages, by unique users over the 90 days ending 2026-09-17
// (Mixpanel "Team Countdown" project, $mp_web_page_view broken down by
// current_url_path). Unique users, not page views: the PWA gets reopened
// daily by a few heavy users, which made the Bruins page look 8x more
// popular than it is. Ordered most popular first, up to 7 per league so a
// league page still has 5 to show after hiding itself. Pages with a single
// visitor and non-countdown pages (homepage, login, about…) are left out.
// Refresh from Mixpanel when this feels stale.
export const POPULAR_PAGES: { league: string; path: string }[] = [
	{ league: 'NFL', path: '/nfl/season' },
	{ league: 'NHL', path: '/nhl' },
	{ league: 'NHL', path: '/nhl/season' },
	{ league: 'NFL', path: '/nfl' },
	{ league: 'NFL', path: '/nfl/buf' },
	{ league: 'NHL', path: '/nhl/tor' },
	{ league: 'WORLDCUP', path: '/worldcup/eng' },
	{ league: 'NHL', path: '/nhl/bos' },
	{ league: 'NFL', path: '/nfl/sea' },
	{ league: 'CFB', path: '/cfb/nd' },
	{ league: 'NHL', path: '/nhl/mtl' },
	{ league: 'NFL', path: '/nfl/kc' },
	{ league: 'CFB', path: '/cfb/mia' },
	{ league: 'NHL', path: '/nhl/wsh' },
	{ league: 'WORLDCUP', path: '/worldcup' },
	{ league: 'NHL', path: '/nhl/van' },
	{ league: 'MLB', path: '/mlb' },
	{ league: 'CFB', path: '/cfb' },
	{ league: 'NBA', path: '/nba' },
	{ league: 'CFB', path: '/cfb/uga' },
	{ league: 'NFL', path: '/nfl/phi' },
	{ league: 'CFB', path: '/cfb/ou' },
	{ league: 'NFL', path: '/nfl/chi' },
	{ league: 'MLB', path: '/mlb/tor' },
	{ league: 'CFB', path: '/cfb/fla' },
	{ league: 'WORLDCUP', path: '/worldcup/can' },
	{ league: 'PWHL', path: '/pwhl' },
	{ league: 'CFL', path: '/cfl' },
	{ league: 'CFL', path: '/cfl/ott' },
	{ league: 'CPL', path: '/cpl/pac' },
	{ league: 'MLB', path: '/mlb/sea' },
	{ league: 'WORLDCUP', path: '/worldcup/por' },
	{ league: 'WORLDCUP', path: '/worldcup/usa' },
	{ league: 'WORLDCUP', path: '/worldcup/mex' },
	{ league: 'WNBA', path: '/wnba' },
	{ league: 'NBA', path: '/nba/tor' },
	{ league: 'WORLDCUP', path: '/worldcup/arg' },
	{ league: 'CFL', path: '/cfl/ssk' },
	{ league: 'MLS', path: '/mls' },
	{ league: 'CFL', path: '/cfl/bc' },
	{ league: 'MLB', path: '/mlb/hou' },
	{ league: 'NBA', path: '/nba/phi' },
	{ league: 'NWSL', path: '/nwsl' },
	{ league: 'MLB', path: '/mlb/cws' },
	{ league: 'CFL', path: '/cfl/wpg' },
	{ league: 'NBA', path: '/nba/atl' },
	{ league: 'NBA', path: '/nba/bos' },
	{ league: 'NBA', path: '/nba/ind' },
	{ league: 'WNBA', path: '/wnba/ind' },
	{ league: 'WNBA', path: '/wnba/pdx' },
	{ league: 'PWHL', path: '/pwhl/ott' },
	{ league: 'MLS', path: '/mls/van' },
	{ league: 'MLS', path: '/mls/clb' },
	{ league: 'WWC', path: '/wwc' },
	{ league: 'MLB', path: '/mlb/bal' },
	{ league: 'CFL', path: '/cfl/mtl' },
	{ league: 'CPL', path: '/cpl/ito' },
	{ league: 'WNBA', path: '/wnba/tor' },
	{ league: 'WNBA', path: '/wnba/dal' },
	{ league: 'PWHL', path: '/pwhl/mtl' },
	{ league: 'MLS', path: '/mls/sea' },
	{ league: 'MLS', path: '/mls/clt' },
	{ league: 'MLS', path: '/mls/orl' },
	{ league: 'NWSL', path: '/nwsl/chi' },
	{ league: 'NSL', path: '/nsl/van' },
]
